# Generated by Django 4.2.16 on 2024-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techshopapp', '0004_feedback_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
