[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
alembic = "^1.13.2"
asyncpg = "^0.30.0"
aiohttp = "^3.10.5"
asyncio = "^3.4.3"


[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pytest = "^8.3.2"